[project]
name = "sensing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adafruit-blinka>=8.68.1",
    "adafruit-circuitpython-lsm6ds>=4.6",
    "rpi-gpio>=0.7.1",
]
